In [8]:
import numpy as np
import sympy as sp
from sympy import symbols, Matrix, eye, simplify,Symbol


x = np.array([2,5])
y = np.array([10,-4])

c = x*y.transpose()
xdot = np.dot(x,y)
ydot = np.dot(y,x)

print("xdot = ", xdot)
print("ydot = ", ydot)
print("c = ", c)

xdot =  0
ydot =  0
c =  [ 20 -20]


In [3]:
import numpy as np

X = np.matrix([[2,1,-1],[1,1,-1],[1,-1,2]])
print(X.shape)
C = X.getH()
Xinv = np.linalg.inv(X)
Xd = np.linalg.det(X)
print("X Determinant",(Xd))
print("X Inverse",Xinv)
print("X Transpose",X.transpose())
print("X Conjugate Transpose",C)
print("c = ", C)


(3, 3)
X Determinant 0
X Inverse [[ 1. -1.  0.]
 [-3.  5.  1.]
 [-2.  3.  1.]]
X Transpose [[ 2  1  1]
 [ 1  1 -1]
 [-1 -1  2]]
X Conjugate Transpose [[ 2  1  1]
 [ 1  1 -1]
 [-1 -1  2]]
c =  [[ 2  1  1]
 [ 1  1 -1]
 [-1 -1  2]]
